### ISSUE TITLE
Tweak "practical substitute" wording

### ISSUE THREAD

**Issue by laughinghan** [berneout/round-robin-license#7]
I'm worried that the noun phrase "practical substitute" sort of sounds like it could mean that it's a practical substitute in most situations; so if the software is really versatile, then a version of it restricted to just one use case (which is sort of not a "practical substitute" for it anymore) wouldn't have to be contributed.

What if we tweak it to be a verb phrase instead?

```diff
- ...that it becomes a practical substitute for this software.
+ ...that it can be practical to substitute it for this software.
```

> You don’t have to contribute any software that only invokes this software’s functionality through the interfaces this software exposes, unless it exposes so much of this software’s interfaces or functionality to users, programmers, or other software that it **can be practical to substitute it** for this software.

Is "can be practical" too vague and open-ended?

There's also the option of being way more verbose, but I don't love it:

```diff
- ...that it becomes a practical substitute for this software.
+ ...that it becomes a practical substitute for a significant portion of this software's functionality.
```

**Comment by kemitchell** [comment]
@laughinghan it was part of the intent of the license, as I understood it, that users could make specialized applications of a more general tool without sharing alike. So, for example, an expense-tracking web application might be little more than decorated shell over a subset of a database's storage, querying, and view functionality. You wouldn't have to share your app. If, however, you modified the database to add a native data type for amounts of currency, then you _would_ have to share the modified database alike.

**Comment by laughinghan** [comment]
Totally—my worry is just that if you modify an open source database to *remove* the native data type for currency (and also add some other stuff), does that seem like it's no longer a "practical substitute" for the original, so its source needn't be published?

**Comment by kemitchell** [comment]
Wouldn't that be a "change" and an "addition", rather than "software that invokes this software's functionality"?

The license put things you might have to contribute in three buckets:
1.  "changes"
2.  "additions"
3.  "software that invokes this software's functionality"

The _Applications_ section speaks only of "software that only invokes this software's functionality...". It doesn't say "changes" or "additions".

IIRC, the third bucket used to read "<ins>other</ins> software that invokes this software's functionality". Perhaps it would be more clear with that word replaced? I probably deleted it to try and avoid debates about where one software begins and another starts.

The removal-of-functionality edge case is interesting. I don't recall ever thinking about it explicitly. And I suppose "additions" tends to suggest a missing "subtractions".

That dig feels more clever than practical. Then again, there's a general rule of legal interpretation that when more than one word is used, they're read in such a way to give each different word a different meaning. If "changes" would usually include "additions", but "additions" is stated in this license and "subtractions" isn't, I could see an argument that subtractions aren't covered. I think it's a weak argument, but I think it can be made.

The temptation is to fall back on another, more technical sounding word, like "modifications". That would bring us very close to prior art in the Mozilla Public License version 2. We sometimes refer to this as "file-based copyleft":

> 1.10. "Modifications" means any of the following:
>
> (a) any file in Source Code Form that results from an addition to, deletion from, or modification of the contents of Covered Software; or
>
> (b) any new file in Source Code Form that contains any Covered Software.

But I think that's mostly hiding behind a technical-sounding word, for false comfort.

**Comment by laughinghan** [comment]
I don't understand the legal technicalities, but to me, "changes" and "modifications" sound the same and don't need clarification or explicit definition, and I think "subtractions" are clearly covered by "changes".

My concern is just that people might think there's a loophole in "practical substitute", but I gave a bad example by mentioning "modifying" the database, total red herring, my bad!

But you don't have to modify the database at all to expose only a subset of the functionality. If I run Rainforest Web Services, and I use precompiled binaries of a Round Robin-licensed database from `apt-get`, and I setup management software to be able to spin up and shut down instances of the database, but my customers are rainforest biologists so I put a proxy between my customers that only allows types they need like strings & floats but not currency, then have I exposed a "practical substitute" for the database?

For my customers, kinda. But in general, it arguably isn't a "practical substitute" because it isn't a substitute for use cases that need the currency data type.

**Comment by kemitchell** [comment]
@laughinghan thanks so much for clarifying.

Running with your Rainforest example: I take it the question is whether the company has to contribute the management software. I _would_ read Round Robin to require that.

The main operative term is obviously:

> You don’t have to contribute any software that only invokes this software’s functionality through the interfaces this software exposes, unless it exposes so much of this software’s interfaces or functionality to users, programmers, or other software that it becomes a practical substitute for this software.

But that's also backed up by this sentence in Copyleft:

> When in doubt, contribute.

I suppose we we could be more emphatic, to exclude motivated readings that "practical substitute" means "practical substitute in all or nearly all use cases":

> You don’t have to contribute any software that only invokes this software’s functionality through the interfaces this software exposes, unless it exposes so much of this software’s interfaces or functionality to users, programmers, or other software that it becomes a practical substitute for this software <ins>for a substantial number of use cases</ins>.

**Comment by laughinghan** [comment]
Right, exactly. My intention was that "can be practical to substitute for" is slightly harder to misread that way, without sacrificing brevity.

Nitpick: I'd suggest "substantial portion of use cases" over "substantial number" because use cases aren't really discrete, I think of it as more of a mass noun than a countable noun.
